"""
The mock-modbus register-map contract (`contracts/modbus/mock-modbus.devices.json`).

TEST-ONLY: read by the dev seeder (`tests/seed_db/`) so the seeded devices and points are
built from exactly what mock-modbus serves. App code must never import
`schemas.tests_models`. The JSON is generated by mock-modbus (`make contract`); these
models only parse it, and reject anything unexpected so a contract change is noticed.
"""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class MockModbusRegister(BaseModel):
    """One register as mock-modbus serves it."""

    model_config = ConfigDict(extra="forbid")

    file: Literal["holding", "input"]
    address: int = Field(..., ge=1, le=65535, description="1-based register number")
    name: str = Field(..., min_length=1)
    width: Literal[16, 32]
    signed: bool
    value_source: Literal["random", "profile_static"]
    unit: str | None
    scale: float = Field(..., gt=0)
    min: int
    max: int
    enum_values: dict[str, str] | None
    bit_flags: dict[str, str] | None


class MockModbusDevice(BaseModel):
    """One simulated device, addressed on the aggregator by `unit_id`."""

    model_config = ConfigDict(extra="forbid")

    unit_id: int = Field(..., ge=1)
    name: str = Field(..., min_length=1)
    device_type: Literal["pv", "bess", "ied"]
    kw_max: float | None
    per_device_port: int
    registers: list[MockModbusRegister]


class MockModbusContract(BaseModel):
    """The whole published register map."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    comment: str = Field(..., alias="$comment")
    contract: Literal["mock-modbus/devices"]
    version: Literal[1]
    register_numbering: Literal["one_based"]
    devices: list[MockModbusDevice] = Field(..., min_length=1)
